### ISSUE TITLE
wish: systemd  ".service" and ".timer" files

### ISSUE THREAD

**Issue by markstos** [kevincobain2000/cache-http#1]
Nice idea. A systemd service file would make it even easier to manager on common Linux distros.

**Comment by kevincobain2000** [comment]
Thank you for the suggestion, it'dd be good to have. Although this is a very simple web server and is a temporary solution until https://github.com/actions/cache/issues/505 gives out full support to GHE.

**Comment by markstos** [comment]
A `.service` and `.timer` file could also be created for the cache clearing function so that as part of installing the project, the cache is getting pruned as well.

**Comment by markstos** [comment]
`systemd` unit files would not be required to be set up if the service is run as a "service container", as described in https://github.com/kevincobain2000/cache-http/pull/8   

And no cron-job / timer would be required if the suggestion to automatically do cache pruning maintenance after new uploads, as suggested in https://github.com/kevincobain2000/cache-http/issues/9

So I'm closing this issue because I think those other approaches make the project easier to use.
